services:
  user-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${USER_DB_PASSWORD}
      MYSQL_DATABASE: ${USER_DB_NAME}
    volumes:
      - ${USER_DATA_PATH}:/var/lib/mysql
    ports:
      - ${USER_DB_BINDING_PORT}:3306
  
  product-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: fcfsProduct
    volumes:
      - ${PRODUCT_DATA_PATH}:/var/lib/mysql
    ports:
      - 4000:3306

  order-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ORDER_DB_PASSWORD}
      MYSQL_DATABASE: ${ORDER_DB_NAME}
    volumes:
      - ${ORDER_DATA_PATH}:/var/lib/mysql
    ports:
      - ${ORDER_DB_BINDING_PORT}:3306

  cache-server:
    image: redis/redis-stack-server:6.2.6-v17
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_CONFIG_PATH}:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_BINDING_PORT}:${REIDS_PORT}
  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - ${KAFKA_DATA_PATH}:/bitnami/kafka
    ports:
      - 9092:9092
      - 9093:9093
      - 29092:29092