# services:
#   config-server:
#     build: ./config-server/.
#     container_name: config-server
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://config-server:8888/actuator/health"]
#       interval: 10s
#       timeout: 5s
#       retries: 3
#     deploy:
#       resources:
#         limits:
#           memory: 1G       # 최대 메모리 1GB
#           cpus: '1.0'      # 최대 CPU 1개
#     volumes:
#       - /c/Users/fatum/OneDrive/Desktop/hanghae-msa/config:/config-repo
#     environment:
#       - "spring.cloud.config.server.native.search-locations=${CONFIG_REPO}"
  
#   eureka-server:
#     build: ./eureka-server/.
#     container_name: eureka-server
#     ports:
#       - 8761:8761
#     deploy:
#       resources:
#         limits:
#           memory: 1G       # 최대 메모리 1GB
#           cpus: '1.0'      # 최대 CPU 1개
  
#   gateway-server:
#     build: ./gateway-service/.
#     container_name: gateway-server
#     environment:
#       - SPRING_CLOUD_CONFIG_URI=${SPRING_CLOUD_CONFIG_URI}
#       - "eureka.client.service-url.default_zone=${EUREKA_URI}"
#     ports:
#       - 8000:8000
#     depends_on:
#       config-server:
#         condition: service_healthy
#     deploy:
#       resources:
#         limits:
#           memory: 1G       # 최대 메모리 1GB
#           cpus: '1.0'      # 최대 CPU 1개
 
#   user-server:
#     build: ./user-service/.
#     container_name: user-service
#     environment:
#       - SPRING_CLOUD_CONFIG_URI=${SPRING_CLOUD_CONFIG_URI}
#       - "eureka.client.service-url.default_zone=${EUREKA_URI}"
#     depends_on:
#       config-server:
#         condition: service_healthy
#     deploy:
#       resources:
#         limits:
#           memory: 1G       # 최대 메모리 1GB
#           cpus: '1.0'      # 최대 CPU 1개
  
#   payment-server:
#     build: ./payment-service/.
#     container_name: payment-service
#     environment:
#       - SPRING_CLOUD_CONFIG_URI=${SPRING_CLOUD_CONFIG_URI}
#       - "eureka.client.service-url.default_zone=${EUREKA_URI}"
#     depends_on:
#       config-server:
#         condition: service_healthy
#     deploy:
#       resources:
#         limits:
#           memory: 1G       # 최대 메모리 1GB
#           cpus: '1.0'      # 최대 CPU 1개

#   product-server:
#     build: ./product-service/.
#     container_name: product-service
#     environment:
#       - SPRING_CLOUD_CONFIG_URI=${SPRING_CLOUD_CONFIG_URI}
#       - "eureka.client.service-url.default_zone=${EUREKA_URI}"
#     depends_on:
#       config-server:
#         condition: service_healthy
#     deploy:
#       resources:
#         limits:
#           memory: 1G       # 최대 메모리 1GB
#           cpus: '1.0'      # 최대 CPU 1개

#   order-server:
#     build: ./order-service/.
#     container_name: order-service
#     environment:
#       - SPRING_CLOUD_CONFIG_URI=${SPRING_CLOUD_CONFIG_URI}
#       - "eureka.client.service-url.default_zone=${EUREKA_URI}"
#       - TZ=Asia/Seoul
#     depends_on:
#       config-server:
#         condition: service_healthy
#     deploy:
#       resources:
#         limits:
#           memory: 1G       # 최대 메모리 1GB
#           cpus: '1.0'      # 최대 CPU 1개