services: 
  user-db:
    image: mysql:9.1.0
    environment:
      MYSQL_ROOT_PASSWORD: ${USER_DB_PASSWORD}
      MYSQL_DATABASE: ${USER_DB_NAME}
    volumes:
      - ${USER_DATA_PATH}:/var/lib/mysql
    ports:
      - ${USER_DB_BINDING_PORT}:3306
    deploy:
      resources:
        limits:
          memory: 1G       # 최대 메모리 1GB
          cpus: '2.0'      # 최대 CPU 2개
  
  product-db:
    image: mysql:9.1.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: fcfsProduct
    volumes:
      - ${PRODUCT_DATA_PATH}:/var/lib/mysql
    ports:
      - ${PRODUCT_DB_BINDING_PORT}:3306
    deploy:
      resources:
        limits:
          memory: 1G       # 최대 메모리 1GB
          cpus: '2.0'      # 최대 CPU 2개

  order-db:
    image: mysql:9.1.0
    environment:
      MYSQL_ROOT_PASSWORD: ${ORDER_DB_PASSWORD}
      MYSQL_DATABASE: ${ORDER_DB_NAME}
    volumes:
      - ${ORDER_DATA_PATH}:/var/lib/mysql
    ports:
      - ${ORDER_DB_BINDING_PORT}:3306
    deploy:
      resources:
        limits:
          memory: 1G       # 최대 메모리 1GB
          cpus: '2.0'      # 최대 CPU 2개
      
  payment-db:
    image: mysql:9.1.0
    container_name: payment-db
    environment:
      MYSQL_ROOT_PASSWORD: ${PAYMENT_DB_PASSWORD}
      MYSQL_DATABASE: ${PAYMENT_DB_NAME}
    volumes:
      - ${PAYMENT_DATA_PATH}:/var/lib/mysql
    ports:
      - ${PAYMENT_DB_BINDING_PORT}:3306
    deploy:
      resources:
        limits:
          memory: 1G       # 최대 메모리 1GB
          cpus: '2.0'      # 최대 CPU 2개

  cache-server:
    image: redis/redis-stack-server:6.2.6-v17
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_CONFIG_PATH}:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_BINDING_PORT}:${REIDS_PORT}
    deploy:
      resources:
        limits:
          memory: 0.5G       # 최대 메모리 0.5GB
          cpus: '2.0'      # 최대 CPU 2개