services:
  redis-master-1:
    container_name: redis-master-1
    image: redis:7.4.2
    volumes:
      - ./redis/redis-master-1.conf:/etc/redis-master-1.conf
    command:
      redis-server /etc/redis-master-1.conf
    ports:
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
      - "7006:7006"

  redis-master-2:
    container_name: redis-master-2
    image: redis:7.4.2
    network_mode: "service:redis-master-1"
    volumes:
      - ./redis/redis-master-2.conf:/etc/redis-master-2.conf
    command:
      redis-server /etc/redis-master-2.conf

  redis-master-3:
    container_name: redis-master-3
    image: redis:7.4.2
    network_mode: "service:redis-master-1"
    volumes:
      - ./redis/redis-master-3.conf:/etc/redis-master-3.conf
    command:
      redis-server /etc/redis-master-3.conf

  redis-replica-1:
    container_name: redis-replica-1
    image: redis:7.4.2
    network_mode: "service:redis-master-1"
    volumes:
      - ./redis/redis-replica-1.conf:/etc/redis-replica-1.conf
    command:
      redis-server /etc/redis-replica-1.conf

  redis-replica-2:
    container_name: redis-replica-2
    image: redis:7.4.2
    network_mode: "service:redis-master-1"
    volumes:
      - ./redis/redis-replica-2.conf:/etc/redis-replica-2.conf
    command:
      redis-server /etc/redis-replica-2.conf

  redis-replica-3:
    container_name: redis-replica-3
    image: redis:7.4.2
    network_mode: "service:redis-master-1"
    volumes:
      - ./redis/redis-replica-3.conf:/etc/redis-replica-3.conf
    command:
      redis-server /etc/redis-replica-3.conf

  redis_cluster_entry:
    image: redis:7.4.2
    network_mode: "service:redis-master-1"
    container_name: redis_cluster_entry
    command: redis-cli --cluster create 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 127.0.0.1:7006 --cluster-yes --cluster-replicas 1
    depends_on:
      - redis-master-1
      - redis-master-2
      - redis-master-3
      - redis-replica-1
      - redis-replica-2
      - redis-replica-3